[build.environment]
NPM_FLAGS = "--prefix=/dev/null"
NODE_VERSION = "18"

[build]
publish = "dist"
command = "vite build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/*"
[headers.values]
cache-control = '''
    max-age=31536000,
    immutable
    '''