export const ladi = [
  {
    "title": "Dona Isabel Que História é Essa",
    "category": "Ladainhas",
    "description": " Mestre Toni Vargas",
    "story": "Song about the history of slavery, resistance and necessary rebellion. Mestre Toni Vergas wrote the song because he believed as everybody else did as a boy the stories that Princess Isabel made the law and that people and the slaves had been freed, when in fact it wasn't quite like that. This song renounces the praises Princess Isabel gets for abolishing slavery, in fact there are many black people who died fighting for freedom, many political fighting, a lot of capoeira and a lot of struggle before the people were freed, it wasn't just Princess Isabel who just wrote the law and made people free.",
    "lyrics": "Iêê\nDona Isabel que história é essa\nHoo Isabel que história é essa\nDe ter feito a abolição\nDe ser princesa boazinha\nQue acabou com a escravidão\nEstou cansado de conversa\nEstou  cansado de ilusão\nAbolição se fez com sangue\nQue inundava esse país\nQue o negro transformou em luta\nCansado de ser infeliz\nAbolição se fez bem antes\nE Ainda há por se fazer agora\nCom a verdade da favela\nDona Isabel\nNão com a mentira da escola\nHo Isabel chegou a hora\nDe se acabar com essa maldade\nDe se ensinar aos nossos filhos\nHo Isabel\nO quanto custa a liberdade\nViva Zumbi, nosso gueirreiro\nQue fez-se herói lá em Palmares\nViva a cultura desse povo\nA liberdade verdadeira\nQue já corria nos quilombos\nDona Isabel\nE já jogava Capoeira\nCamaradinha\nO que vai fazer?\nIêê, que vai fazer, camará\nIêê, com Capoeira\nIêê,  com Capoeira, camará\nIêê, menino e bom\nIêê, menino e bom,  camará\nIêê, sabe jogar\nIêê, sabe jogar,  camará",
    "translations": "Iêê\nIêê\nDona Isabel que história é essa\nDona Isabel what is this history?\nHoo Isabel que história é essa\nHoo Isabel what is this history\nDe ter feito a abolição\nThat you made the abolition\nDe ser princesa boazinha\nThat you are a good princess\nQue acabou com a escravidão\nThat freed slavery\nEstou cansado de conversa\nI am tired of talking\nEstou  cansado de ilusão\nI am tired of illusions\nAbolição se fez com sangue\nAbolition was done with blood\nQue inundava esse país\nThat flooded this country\nQue o negro transformou em luta\nBecause the black decided to fight\nCansado de ser infeliz\nTired of being unhappy\nAbolição se fez bem antes\nAbolition was made well before\nE Ainda há por se fazer agora\nAnd still there to be done now\nCom a verdade da favela\nWith the truth of the slum\nDona Isabel\nDona Isabel\nNão com a mentira da escola\nNot with the lies of school\nHo Isabel chegou a hora\nHo Miss Isabel the time has come\nDe se acabar com essa maldade\nTo end this evil\nDe se ensinar aos nossos filhos\nTo teach our children\nHo Isabel\nHo Isabel\nO quanto custa a liberdade\nHow much the freedom cost\nViva Zumbi, nosso gueirreiro\nLong live Zumbi, our warrior\nQue fez-se herói lá em Palmares\nThat became hero in Palmares\nViva a cultura desse povo\nLong live the culture of this people\nA liberdade verdadeira\nThe True freedom\nQue já corria nos quilombos\nBecause I already ran the Quilombos\nDona Isabel\nDona Isabel\nE já jogava Capoeira\nAnd already played Capoeira\nCamaradinha\nCamaradinha\nO que vai fazer?\nWhat are you going to do?\nIêê, que vai fazer, camará\nIêê, what are you going to do, camará\nIêê, com Capoeira\nIêê, with Capoeira\nIêê,  com Capoeira, camará\nIêê, with Capoeira, camará\nIêê, menino e bom\nIêê, boy is good\nIêê, menino e bom,  camará\nIêê,  boy is good,  camará\nIêê, sabe jogar\nIêê, know how to play\nIêê, sabe jogar,  camará\nIêê, know how to play, camará"
  },
  {
    "title": "Eu Ja Vivo Enjoado",
    "category": "Ladainhas",
    "story": "This song is about how nothing comes easy without hard work. The person who sings the ladainha cries out \"Ieeeeeeee\" (pronounced YaaaaaaaaY) to call to order the attendees of the roda, that the roda is starting. The ladainha ends with \"Camará\", \"Camaradinho\" (fits better rhythmically), or conversely, \"É hora, hora\" (It's the hour). This tagline marks the end of the ladainha and the beginning of the chula, or more properly louvação (praise).",
    "lyrics": "",
    "translations": ""
  },
  {
    "title": "Igreja Do Bonfim",
    "category": "Ladainhas",
    "description": " Mestre Paulo Dos Anjos",
    "story": "Igreja do Bonfim is the most famous Catholic church in Salvador",
    "lyrics": "Igreja do Bonfim\nE Mercado Modelo\nLadeira do Pelourinho\nE Baixa do Sapateiro\nFalar na Cidade Alta\nEu me lembrei do Terreiro\nIgreja de São Francisco\nE Praça da Sé\nA onde fica as baianas\nVendendo acarajé\nPor falar em Itapoã\nLagoa do Abaeté\nCamaradinho\nÊ viva meu Mestre\nIê viva o meu mestre\nCamará\nÊ viva meu Mestre\nIê viva o meu mestre\nCamará\nEi quem me ensinou\nEi quem me ensinou\nCamará\nEi volta do mundo\nEi volta do mundo\nCamará\nEi que o mundo deu\nEi que o mundo deu\nCamará\nEi que o mundo dá\nEi que o mundo dá\nCamará",
    "translations": "Igreja do Bonfim\nThe church of Bonfim\nE Mercado Modelo\nAnd the Mercado Modelo\nLadeira do Pelourinho\nThe slope of Pelourinho\nE Baixa do Sapateiro\nBellow of Sapateiro\nFalar na Cidade Alta\nSpeaks about the high city\nEu me lembrei do Terreiro\nMakes me remember the Terreiro\nIgreja de São Francisco\nThe church of São Francisco\nE Praça da Sé\nAnd the Sé (Cathedral) square\nA onde fica as baianas\nThis is where the Baianas\nVendendo acarajé\nselling acarajé (Typical food)\nPor falar em Itapoã\nTo speak of Itapoã\nLagoa do Abaeté\nThe lake of Abaeté\nCamaradinho\nFriend\nÊ viva meu Mestre\nHey long live my Master\nIê viva o meu mestre\nHey long live my master\nCamará\nFriend\nÊ viva meu Mestre\nHey long live my Master\nIê viva o meu mestre\nHey long live my master\nCamará\nFriend\nEi quem me ensinou\nHey who taught me\nEi quem me ensinou\nHey who taught me\nCamará\nFriend\nEi volta do mundo\nHey around the world\nEi volta do mundo\nHey around the world\nCamará\nFriend\nEi que o mundo deu\nHey what the world gave\nEi que o mundo deu\nHey what the world gave\nCamará\nFriend\nEi que o mundo dá\nHey what the world gives\nEi que o mundo dá\nHey what the world gives\nCamará\nFriend"
  },
  {
    "title": "Ladeira Do Pelourinho",
    "category": "Ladainhas",
    "description": " Mestre Jogo de Dentro",
    "story": "“Pelourinho” means pillory, and Salvador’s pelourinho last stood at the top of the sloping Largo do Pelourinho, final point in a journey which began in the city’s first open market in the Praça da Feira (today known as Praça Municipal — the open square at the top of the Elevador Lacerda). The pelourinho stood at the market’s center. Salvador is the capital of Bahia, whose large bay and proximity to Africa made it a major port for the slave trade. The descendants of slaves have taken over this symbolic spot, an entry point for African culture in the New World.",
    "lyrics": "Ladeira do Pelourinho\nLadeira do Pelourinho, ora meu Deus\nOnde eu comecei a andar\nNo Forte Santo Antônio\nEu comecei praticar\nA Capoeira de Angola\nJoão Pequeno táva lá\nOs turistos todos os dias\nIam nos prestigiar\nO governador vendo isso\nTratou logo de acabar\nVendo Capoeira Angola\nEra dança de matar\nOlha, eu disse, governador\nNão faça isso mais não\nCapoeira de Angola é\nUma grande tradição\nQuando eu pego na viola\nora meu Deus\nDói até meu coração\nE o jogo de Capoeira\nÉ um jogo de irmão\nQuando eu entro na roda\nNão tem agressão\nEu jogo a Capoeira\nDo fundo do meu coração\nAgradeço a meu Deus\nE ao Mestre João\nPor me ensinar a Capoeira\nCom toda dedicação\nCamará\nIe Viva meu deus…\nIe Viva meu deus…\nCamará\nIê Viva meu Mestre\nIê Viva meu Mestre\nCamará\nIê quem me ensinou\nIê quem me ensinou\nCamará\nIê a capoeira\nIê a capoeira\nCamará\nIê galou cantou\nIê galou cantou\nCamará\nIê cocorroco\nIê cocorroco\nCamará\nIê é hora é hora\nIê é hora é hora\nCamará\nIê Vamonos embora\nIê Vamonos embora\nCamará",
    "translations": "Ladeira do Pelourinho\nAt the slope of Pelourinho\nLadeira do Pelourinho, ora meu Deus\nAt the slope of Pelourinho,oh my God\nOnde eu comecei a andar\nWhere I started walking\nNo Forte Santo Antônio\nAt Fortress Santo Antônio\nEu comecei praticar\nI started practicing\nA Capoeira de Angola\nThe Capoeira Angola\nJoão Pequeno táva lá\nJoão Pequeno was there\nOs turistos todos os dias\nThe daily tourists\nIam nos prestigiar\nAppreciating us\nO governador vendo isso\nThe governor seeing this\nTratou logo de acabar\nCommand to end this soon\nVendo Capoeira Angola\nViewing Capoeira Angola\nEra dança de matar\nLike it was dance of kill\nOlha, eu disse, governador\nLook, I said, Governor\nNão faça isso mais não\nDon’t do it no more\nCapoeira de Angola é\nCapoeira Angola is\nUma grande tradição\nA great tradition\nQuando eu pego na viola\nWhen I picked up my viola\nora meu Deus\noh my God\nDói até meu coração\nIt hurts my heart\nE o jogo de Capoeira\nAnd the game of Capoeira\nÉ um jogo de irmão\nIt is a game of brothers\nQuando eu entro na roda\nWhen I enter the roda\nNão tem agressão\nHas no aggression\nEu jogo a Capoeira\nI play Capoeira\nDo fundo do meu coração\nFrom the bottom of my heart\nAgradeço a meu Deus\nI thank my God\nE ao Mestre João\nAnd the Master Joao\nPor me ensinar a Capoeira\nFor teach me Capoeira\nCom toda dedicação\nWith all the dedication\nCamará\nFriend\nIe Viva meu deus…\nIe Long live my master\nIe Viva meu deus…\nIe Long live my master\nCamará\nFriend\nIê Viva meu Mestre\n\nIê Viva meu Mestre\n\nCamará\nFriend\nIê quem me ensinou\n\nIê quem me ensinou\n\nCamará\nFriend\nIê a capoeira\n\nIê a capoeira\n\nCamará\nFriend\nIê galou cantou\n\nIê galou cantou\n\nCamará\nFriend\nIê cocorroco\n\nIê cocorroco\n\nCamará\nFriend\nIê é hora é hora\n\nIê é hora é hora\n\nCamará\nFriend\nIê Vamonos embora\n\nIê Vamonos embora\n\nCamará\nFriend"
  },
  {
    "title": "Menino Quem Foi Seu Mestre",
    "category": "Ladainhas",
    "description": " Mestre João Pequeno",
    "lyrics": "Menino, quem foi seu mestre ?\nquem te ensinou a brincar\no teu mestre foi Besouro\naprendeu com Manganga\neu aprendi com Pastinha\nquero contigo Brincar\na capoeira de angola\nCapoeira de Angola\na africano quem mandou\nNa capital de Salvador\nfoi pastinha que me ensinou\nna roda de capoeira\nreconheço esse valor",
    "translations": "Menino, quem foi seu mestre ?\nBoy, who was your teacher?\nquem te ensinou a brincar\nWho taught you to play\no teu mestre foi Besouro\nyour teacher was Besouro\naprendeu com Manganga\nlearned with Manganga\neu aprendi com Pastinha\nI learned from Pastinha\nquero contigo Brincar\nI want you Play with you\na capoeira de angola\nCapoeira de Angola\nCapoeira de Angola\nCapoeira de Angola\na africano quem mandou\nthe african who sent\nNa capital de Salvador\nIn the capital of Salvador\nfoi pastinha que me ensinou\nIt was Pastinha that taught me\nna roda de capoeira\nin the capoeira roda\nreconheço esse valor\nrecognise this value"
  },
  {
    "title": "Meu Mestre é Pequenininho",
    "category": "Ladainhas",
    "description": " Mestre Toni Vargas",
    "lyrics": "Meu mestre é pequenininho\nMeu mestre é pequenininho\nQuando quer fica menor\nPode ser seixo miúdo\nOu ter o brilho do sol\nQue te cega\nTu procura, procura não acha\nSe tu vem por baixo ele voa\nSe tu vem voando ele abaixa\nMeu mestre é pequenininho\nCuidado tu pode nem vê\nQue quando ele abre a ginga\nDerrama na roda mandinga\nE fica maior que você camará\nIé o mestre é bom\nIé o mestre é bom, camará\nIé Mestre Peixinho\nIé Mestre Peixinho, camará\nIé que me ensinou\nIé que me ensinou, camará\nIé que me formou\nIé que me formou, camará\nIé é le da senzala\nIé éle da senzala, camará\nIé sabe jogar\nIé sabe jogar, camará",
    "translations": "Meu mestre é pequenininho\nMy master is tiny\nMeu mestre é pequenininho\nMy master is tiny\nQuando quer fica menor\nWhen either wants to be smaller\nPode ser seixo miúdo\nIt can be a pebble\nOu ter o brilho do sol\nOr it can be the glow of the sun\nQue te cega\nThat blinds you\nTu procura, procura não acha\nYou quest, quest but can’t find\nSe tu vem por baixo ele voa\nIf you come underneath he fly\nSe tu vem voando ele abaixa\nIf you come flying he lowers\nMeu mestre é pequenininho\nMy master is tiny\nCuidado tu pode nem vê\nBeware you maybe can’t see\nQue quando ele abre a ginga\nThat when he opens the ginga\nDerrama na roda mandinga\nPour mandinga in the roda\nE fica maior que você camará\nAnd becomes bigger than you, friend\nIé o mestre é bom\nIé the master is good\nIé o mestre é bom, camará\nIé the master is good, camará\nIé Mestre Peixinho\nIé Mestre Peixinho\nIé Mestre Peixinho, camará\nIé Mestre Peixinho, camará\nIé que me ensinou\nIt's what you taught me\nIé que me ensinou, camará\nIt's what you taught me, camará\nIé que me formou\nIé that formed me\nIé que me formou, camará\nIé that formed me, camará\nIé é le da senzala\nIé he from the senzala\nIé éle da senzala, camará\nIé he from the senzala, camará\nIé sabe jogar\nIé know to play\nIé sabe jogar, camará\nIé know to play, camará"
  },
  {
    "title": "Meu Mestre é Pequenininho",
    "category": "Ladainhas",
    "description": " Mestre Toni Vargas",
    "lyrics": "Meu mestre é pequenininho\nMeu mestre é pequenininho\nQuando quer fica menor\nPode ser seixo miúdo\nOu ter o brilho do sol\nQue te cega\nTu procura, procura não acha\nSe tu vem por baixo ele voa\nSe tu vem voando ele abaixa\nMeu mestre é pequenininho\nCuidado tu pode nem vê\nQue quando ele abre a ginga\nDerrama na roda mandinga\nE fica maior que você camará\nIé o mestre é bom\nIé o mestre é bom, camará\nIé Mestre Peixinho\nIé Mestre Peixinho, camará\nIé que me ensinou\nIé que me ensinou, camará\nIé que me formou\nIé que me formou, camará\nIé é le da senzala\nIé éle da senzala, camará\nIé sabe jogar\nIé sabe jogar, camará",
    "translations": "Meu mestre é pequenininho\nMy master is tiny\nMeu mestre é pequenininho\nMy master is tiny\nQuando quer fica menor\nWhen either wants to be smaller\nPode ser seixo miúdo\nIt can be a pebble\nOu ter o brilho do sol\nOr it can be the glow of the sun\nQue te cega\nThat blinds you\nTu procura, procura não acha\nYou quest, quest but can’t find\nSe tu vem por baixo ele voa\nIf you come underneath he fly\nSe tu vem voando ele abaixa\nIf you come flying he lowers\nMeu mestre é pequenininho\nMy master is tiny\nCuidado tu pode nem vê\nBeware you maybe can’t see\nQue quando ele abre a ginga\nThat when he opens the ginga\nDerrama na roda mandinga\nPour mandinga in the roda\nE fica maior que você camará\nAnd becomes bigger than you, friend\nIé o mestre é bom\nIé the master is good\nIé o mestre é bom, camará\nIé the master is good, camará\nIé Mestre Peixinho\nIé Mestre Peixinho\nIé Mestre Peixinho, camará\nIé Mestre Peixinho, camará\nIé que me ensinou\nIt's what you taught me\nIé que me ensinou, camará\nIt's what you taught me, camará\nIé que me formou\nIé that formed me\nIé que me formou, camará\nIé that formed me, camará\nIé é le da senzala\nIé he from the senzala\nIé éle da senzala, camará\nIé he from the senzala, camará\nIé sabe jogar\nIé know to play\nIé sabe jogar, camará\nIé know to play, camará"
  },
  {
    "title": "Nego Veio",
    "category": "Ladainhas",
    "description": " Mestre Joel",
    "story": "Candomblé more well known to many non-Brazilian Capoeiristas as this was the form of religion that developed around Salvador Brasil, which is also the home of Capoeira Angola. Candomblé is also a syncretic religion that evolves worship of the Orixás. It surfaced through a process of syncretism between the traditional Yoruba religion of West Africa and the Roman Catholic form of Christianity.",
    "lyrics": "Nego veio de Angola tu veio para assinar\nTu trouxe capoeira e candomble e Ogum\nE o rei dos orixa\nEh viva meu mestre\nEh e hora e hora\nEh galo cantou\nEh viva Bahia\nEh viva seu Bimba\nEh viva Pastinhá\nEh volta do mundo\nEh e hora e hora\nEh galo cantou\nEh viva Bahia\nEh viva meu Mestre\nEh viva seu Bimba\nEh viva Pastinhá\nEh volta do Mundo\nLa no céu vai quem merece\nAqui na terra vale quem tem\nLa no céu tem três carreirinhás\nE la no céu há três estrelas\nUma e chámada de Aberre\nOutra Bimba e Pastinhá\nEh viva meu mestre!\nEh e hora e hora!\nEh galo cantou!\nEh viva Zumbi!\nEh viva Aberre!\nEh viva Pastinhá!\nEh viva seu Bimba!\nEh volta do mundo!",
    "translations": "Nego veio de Angola tu veio para assinar\nNego came from Angola you came to sign\nTu trouxe capoeira e candomble e Ogum\nYou brought capoeira and candomble and Ogum\nE o rei dos orixa\nAnd the king of the orixa\nEh viva meu mestre\nHey long live my master\nEh e hora e hora\nEh it's time it's time\nEh galo cantou\nHey rooster sang\nEh viva Bahia\nHey long live Bahia\nEh viva seu Bimba\nHey long live your Bimba\nEh viva Pastinhá\nHey long live Pastinhá!\nEh volta do mundo\nEh around the world\nEh e hora e hora\nEh it's time it's time\nEh galo cantou\nHey rooster sang\nEh viva Bahia\nHey long live Bahia\nEh viva meu Mestre\nHey long live my mestre\nEh viva seu Bimba\nHey long live your Bimba\nEh viva Pastinhá\nHey long live Pastinhá!\nEh volta do Mundo\nHey around the world\nLa no céu vai quem merece\nThere in heaven goes who deserves it\nAqui na terra vale quem tem\nHere on earth, whoever has\nLa no céu tem três carreirinhás\nThere in heaven there are three careers\nE la no céu há três estrelas\nAnd there in the sky there are three stars\nUma e chámada de Aberre\nOne and call from Aberre\nOutra Bimba e Pastinhá\nAnother Bimba and Pastinha\nEh viva meu mestre!\nHey long live my mestre!\nEh e hora e hora!\nEh it's time it's time\nEh galo cantou!\nHey rooster sang!\nEh viva Zumbi!\nHey long live Zumbi!\nEh viva Aberre!\nHey long live Aberre!\nEh viva Pastinhá!\nHey long live Pastinha!\nEh viva seu Bimba!\nHey long live your Bimba!\nEh volta do mundo!\nEh around the World!"
  },
  {
    "title": "O Brasil Disse Que Sim",
    "category": "Ladainhas",
    "lyrics": "O Brasil disse que sim\nO Brasil disse que não\nO Brasil disse que sim\nMas o Japão disse que não\nDuas esquadra poderosa\nPra brigar com alemão\nDei meu nome, agora eu vou\nNum sorteio militar\nQuem não pode com mandinga\nNão carrega patuá\nQuem não pode não inventa\nDeixa quem pode inventar\nÊ, ai di lê lê\nÊ, ai di lê lê, camará\nÊ, que vai fazer\nÊ, que vai fazer, camará",
    "translations": "O Brasil disse que sim\nBrazil said yes\nO Brasil disse que não\nBrazil said no\nO Brasil disse que sim\nBrazil said yes\nMas o Japão disse que não\nBut Japan said no\nDuas esquadra poderosa\nTwo powerful fleet\nPra brigar com alemão\nTo fight with German\nDei meu nome, agora eu vou\nI gave my name, now I’ll\nNum sorteio militar\nIn a draft lottery\nQuem não pode com mandinga\nWho can’t with mandinga\nNão carrega patuá\nNot walk with patuá\nQuem não pode não inventa\nWho can’t invent\nDeixa quem pode inventar\nLet who can invent\nÊ, ai di lê lê\nÊ, ai di lê lê\nÊ, ai di lê lê, camará\nÊ, ai di lê lê, camará\nÊ, que vai fazer\nÊ, what will you do\nÊ, que vai fazer, camará\nÊ, what will you do, camará"
  },
  {
    "title": "O Mundo De Deus É Grande",
    "category": "Ladainhas",
    "description": " Mestre Suassuna",
    "lyrics": "O mundo de Deus é grande\nDeus tá numa mão fechada\nO pouco com Deus é muito\nO muito sem Deus é nada\nNoite de escuro não serve\nPrá caçar de madrugada\nCaçador dá muitos tiros\nÔiaiá, de manhã não acha nada\nVeado corre é pulando\nCotia corre na trilha\nSe eu fosse governador\nAh, Meu Deus, manobrasse a Bahia\nMarinheiro absoluta\nChegou pintando arrelia\nIsso que marujo faz\nComigo ele não faria\nCamaradinha\nÉ hora é hora\nIê, é hora é hora Camará\nIê, galo cantou\nIê, galo cantou Camará\nIê, cocorocô\nIê, cocorocô Camará",
    "translations": "O mundo de Deus é grande\nThe world of God is big\nDeus tá numa mão fechada\nGod is with close hand\nO pouco com Deus é muito\nThe bit with God is a lot\nO muito sem Deus é nada\nA lot without God is nothing\nNoite de escuro não serve\nDark night doesn’t help\nPrá caçar de madrugada\nTo hunt early in the morning\nCaçador dá muitos tiros\nHunter gives many shots\nÔiaiá, de manhã não acha nada\nÔiaiá, in the morning finds nothing\nVeado corre é pulando\nDeer runs and jumps\nCotia corre na trilha\nCotia runs on the trail\nSe eu fosse governador\nIf I were governor\nAh, Meu Deus, manobrasse a Bahia\nAh, my God, maneuver Bahia\nMarinheiro absoluta\nAbsolute sailor\nChegou pintando arrelia\nHe arrived painting arrelia\nIsso que marujo faz\nThat's what sailor does\nComigo ele não faria\nwith me he wouldn't do\nCamaradinha\nMy friend\nÉ hora é hora\nIt's time it's time\nIê, é hora é hora Camará\nHey, it's time, it's time Camará\nIê, galo cantou\nHey, rooster sang\nIê, galo cantou Camará\nHey, rooster sang Camará\nIê, cocorocô\nHey, cocorocô\nIê, cocorocô Camará\nHey, cocorocô Camará"
  },
  {
    "title": "O Negro Religioso",
    "category": "Ladainhas",
    "description": " Mestre Marrom",
    "story": "Song about slaves who brought their African beliefs in spirits and magic to Brazil. While the slaves outwardly worshipped under the Catholic faith, they covertly carried on their religious beliefs since slave owners prohibited slaves from practising their African form of worship.",
    "lyrics": "O Negro Religioso\nDentro de casa tem seu gonga\nO Negro Religioso\nDentro de casa tem seu gonga\nPorém desde o cativeira\nMudou de nome o seu Orixá\nE assim dona Janaína é Nossa Senhora da Conceicão\nOxum e das Candeias\nOxóssi é São Sebastião\nSão Lázaro é Omolu\nSão Jorge é Ogum\nSantana é Nanâ\nE assim São Bartolomeu é Oxumaré\nSo Pedro é Xangó\nObá é Joana D’arc\nPai Oxalá é Nosso Senhor",
    "translations": "O Negro Religioso\nThe Religious Black\nDentro de casa tem seu gonga\nInside the house there is a gong\nO Negro Religioso\nThe Religious Black\nDentro de casa tem seu gonga\nInside the house there is a gong\nPorém desde o cativeira\nBut since captivity\nMudou de nome o seu Orixá\nYour Orixá changed its name\nE assim dona Janaína é Nossa Senhora da Conceicão\nAnd so Dona Janaína is Our Lady of the Conception\nOxum e das Candeias\nOxum and Candeias\nOxóssi é São Sebastião\nOxóssi is Saint Sebastian\nSão Lázaro é Omolu\nSaint Lazarus is Omolu\nSão Jorge é Ogum\nSaint George is Ogum\nSantana é Nanâ\nSaint Anne is Nanâ\nE assim São Bartolomeu é Oxumaré\nAnd so Saint Bartholomew is Oxumaré\nSo Pedro é Xangó\nSo Pedro is Xangó\nObá é Joana D’arc\nObá is Joana D’arc\nPai Oxalá é Nosso Senhor\nFather Oxalá is Our Lord"
  },
  {
    "title": "Olha Lá Siri De Mangue",
    "category": "Ladainhas",
    "description": " Mestre Waldemar",
    "lyrics": "",
    "translations": ""
  },
  {
    "title": "Pareço Ganga Zumbi",
    "category": "Ladainhas",
    "description": " Mestre Leopoldina",
    "story": "Zumbi was one of the last leaders of Quilombo dos Palmares. Considered one of the great leaders and symbol of resistance to slavery.",
    "lyrics": "Alguém me disse\nPareço Ganga Zumbi\nFoi o Rei lá dos Palmares\nE outros já me disseram\nQue na outra encarnação\nEu era rico, muito rico\nEu tinha muita fazenda\nE grande canavial\nE eu era bom patrão\nSó mulher eu tinha nove\nSó mulher eu tinha nove\nCom idades variadas\nMais agora, O que eu tenho?\nNem sequer tenho casa pra morar\nNem dinheiro pra gastar\nMas tenho a Graça Divina\nQue é minha companheira\nE esta grande amizade\nDentro do meu coração\nCamarada\nIê galo cantou\nIê galo cantou, camará\nIê cocôrocô\nIê cocôrocô, camará\nIê viva meu Mestre\nIê viva meu Mestre, camará\nViva Mestre meu\nIê ele é Mestre meu, camará\nFoi quem me ensinou\nIê foi quem me ensinou, camará\nToda malandragem\nIê a malandragem, camará\nDa capoeiragem\nIê capoeiragem, camará\nE é hora é hora\nIê é hora é hora, camará\nVamonos embora\nIê vamos embora, camará",
    "translations": "Alguém me disse\nSomeone told me\nPareço Ganga Zumbi\nI look like Ganga Zumbí\nFoi o Rei lá dos Palmares\nLook there, He was the king in Palmares\nE outros já me disseram\nOthers already told me\nQue na outra encarnação\nThat in another incarnation\nEu era rico, muito rico\nI was rich, very rich\nEu tinha muita fazenda\nI had a lot of farm\nE grande canavial\nAnd a big sugar cane plantation\nE eu era bom patrão\nAnd I was a good boss\nSó mulher eu tinha nove\nJust women I had nine\nSó mulher eu tinha nove\nJust women I had nine\nCom idades variadas\nOf different ages\nMais agora, O que eu tenho?\nBut now what do I have?\nNem sequer tenho casa pra morar\nI don't even have a house to live\nNem dinheiro pra gastar\nNot even money to spend\nMas tenho a Graça Divina\nBut I have the Divine Grace\nQue é minha companheira\nWho is my companion\nE esta grande amizade\nAnd this great friendship\nDentro do meu coração\nDeep in my heart\nCamarada\nComrade\nIê galo cantou\nHey rooster crowed\nIê galo cantou, camará\nHey rooster crowed, comrade\nIê cocôrocô\nHey Cock-a-doodle doo\nIê cocôrocô, camará\nHey Cock-a-doodle doo, comrade\nIê viva meu Mestre\nBe alive my Master\nIê viva meu Mestre, camará\nBe alive my Master, comrade\nViva Mestre meu\nLong live my master\nIê ele é Mestre meu, camará\nHey he is my Master, comrade\nFoi quem me ensinou\nIt was you who taught me\nIê foi quem me ensinou, camará\nHey, it was you who taught me, comrade\nToda malandragem\nAll trickery\nIê a malandragem, camará\nHey, the trickery, comrade\nDa capoeiragem\nFrom capoeiragem\nIê capoeiragem, camará\nHey capoeiragem, camará\nE é hora é hora\nAnd it's time, it's time\nIê é hora é hora, camará\nHey it's time, it's time, camará\nVamonos embora\nLet's go\nIê vamos embora, camará\nHey let's go, comrade"
  },
  {
    "title": "Quando Tinha Dinheiro",
    "category": "Ladainhas",
    "description": " Mestre Joel",
    "lyrics": "",
    "translations": ""
  },
  {
    "title": "Vencer",
    "category": "Ladainhas",
    "description": " Mestre Moraes",
    "lyrics": "Se vencer uma batalha\nSe vencer uma batalha\nÉ matar o perdedor\nNa guerra que vivo em vida\nNão me vejo ganhador\nPois sem matar nem ferir\nAi meu Deus\nEu me sinto vencedor\nA luz da experiência\nA luz da experiência\nO caminhar nas estradas\nO cruzar encruzilhadas\nMe ensinou a jogar\nJogar o jogo da vida\nNa vida vencer o jogador\nO jogar pela vitória\nEntristece o jogador\nQuando pensa que venceu\nVê que é o perdedor",
    "translations": "Se vencer uma batalha\nIf I win a battle\nSe vencer uma batalha\nIf I win a battle\nÉ matar o perdedor\nAnd kill the loser\nNa guerra que vivo em vida\nIn the war in which I live life\nNão me vejo ganhador\nI don’t see myself as a winner\nPois sem matar nem ferir\nBecause without killing or injuring\nAi meu Deus\nOh my god\nEu me sinto vencedor\nI feel winner\nA luz da experiência\nThe light of experience\nA luz da experiência\nThe light of experience\nO caminhar nas estradas\nOr walking on the paths\nO cruzar encruzilhadas\nOr crossing crossroads\nMe ensinou a jogar\nTaught me to play\nJogar o jogo da vida\nPlay the game of life\nNa vida vencer o jogador\nIn life win who plays\nO jogar pela vitória\nA play for a victory\nEntristece o jogador\nUpsetting the player\nQuando pensa que venceu\nWhen he thinks that he won\nVê que é o perdedor\nHe sees that he is the loser"
  }
]
